# Generated by Django 5.1.1 on 2024-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('ano', models.IntegerField(max_length=4)),
                ('tipo_veiculo', models.CharField(max_length=45)),
                ('situacao', models.CharField(max_length=1)),
            ],
        ),
    ]
